/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_WIFI_SAMPLE_STRUCTURE_PB_H_INCLUDED
#define PB_WIFI_SAMPLE_STRUCTURE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(4) wifi_IPAddr_ipv4_t;
typedef PB_BYTES_ARRAY_T(16) wifi_IPAddr_ipv6_t;
/* IP address */
typedef struct _wifi_IPAddr {
    wifi_IPAddr_ipv4_t ipv4; /* 4 bytes */
    wifi_IPAddr_ipv6_t ipv6; /* 16 bytes */
} wifi_IPAddr;

typedef PB_BYTES_ARRAY_T(33) wifi_WifiSoftAPInfo_ssid_t;
typedef PB_BYTES_ARRAY_T(6) wifi_WifiSoftAPInfo_bssid_t;
/* WiFi SoftAP info */
typedef struct _wifi_WifiSoftAPInfo {
    int32_t device_count;
    int32_t state;
    bool has_ip_address;
    wifi_IPAddr ip_address;
    wifi_WifiSoftAPInfo_ssid_t ssid;
    wifi_WifiSoftAPInfo_bssid_t bssid;
    int32_t security;
    uint32_t channel;
    uint32_t frequency;
} wifi_WifiSoftAPInfo;

typedef struct _wifi_WifiSoftAPList {
    pb_size_t ap_list_count;
    wifi_WifiSoftAPInfo ap_list[20];
} wifi_WifiSoftAPList;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define wifi_IPAddr_init_default                 {{0, {0}}, {0, {0}}}
#define wifi_WifiSoftAPInfo_init_default         {0, 0, false, wifi_IPAddr_init_default, {0, {0}}, {0, {0}}, 0, 0, 0}
#define wifi_WifiSoftAPList_init_default         {0, {wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default, wifi_WifiSoftAPInfo_init_default}}
#define wifi_IPAddr_init_zero                    {{0, {0}}, {0, {0}}}
#define wifi_WifiSoftAPInfo_init_zero            {0, 0, false, wifi_IPAddr_init_zero, {0, {0}}, {0, {0}}, 0, 0, 0}
#define wifi_WifiSoftAPList_init_zero            {0, {wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero, wifi_WifiSoftAPInfo_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define wifi_IPAddr_ipv4_tag                     1
#define wifi_IPAddr_ipv6_tag                     2
#define wifi_WifiSoftAPInfo_device_count_tag     1
#define wifi_WifiSoftAPInfo_state_tag            2
#define wifi_WifiSoftAPInfo_ip_address_tag       3
#define wifi_WifiSoftAPInfo_ssid_tag             4
#define wifi_WifiSoftAPInfo_bssid_tag            5
#define wifi_WifiSoftAPInfo_security_tag         6
#define wifi_WifiSoftAPInfo_channel_tag          7
#define wifi_WifiSoftAPInfo_frequency_tag        8
#define wifi_WifiSoftAPList_ap_list_tag          1

/* Struct field encoding specification for nanopb */
#define wifi_IPAddr_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    ipv4,              1) \
X(a, STATIC,   SINGULAR, BYTES,    ipv6,              2)
#define wifi_IPAddr_CALLBACK NULL
#define wifi_IPAddr_DEFAULT NULL

#define wifi_WifiSoftAPInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device_count,      1) \
X(a, STATIC,   SINGULAR, INT32,    state,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ip_address,        3) \
X(a, STATIC,   SINGULAR, BYTES,    ssid,              4) \
X(a, STATIC,   SINGULAR, BYTES,    bssid,             5) \
X(a, STATIC,   SINGULAR, INT32,    security,          6) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           7) \
X(a, STATIC,   SINGULAR, UINT32,   frequency,         8)
#define wifi_WifiSoftAPInfo_CALLBACK NULL
#define wifi_WifiSoftAPInfo_DEFAULT NULL
#define wifi_WifiSoftAPInfo_ip_address_MSGTYPE wifi_IPAddr

#define wifi_WifiSoftAPList_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  ap_list,           1)
#define wifi_WifiSoftAPList_CALLBACK NULL
#define wifi_WifiSoftAPList_DEFAULT NULL
#define wifi_WifiSoftAPList_ap_list_MSGTYPE wifi_WifiSoftAPInfo

extern const pb_msgdesc_t wifi_IPAddr_msg;
extern const pb_msgdesc_t wifi_WifiSoftAPInfo_msg;
extern const pb_msgdesc_t wifi_WifiSoftAPList_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define wifi_IPAddr_fields &wifi_IPAddr_msg
#define wifi_WifiSoftAPInfo_fields &wifi_WifiSoftAPInfo_msg
#define wifi_WifiSoftAPList_fields &wifi_WifiSoftAPList_msg

/* Maximum encoded size of messages (where known) */
#define WIFI_SAMPLE_STRUCTURE_PB_H_MAX_SIZE      wifi_WifiSoftAPList_size
#define wifi_IPAddr_size                         24
#define wifi_WifiSoftAPInfo_size                 114
#define wifi_WifiSoftAPList_size                 2320

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
