/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "sample_structure.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wifi_IPAddr, wifi_IPAddr, AUTO)


PB_BIND(wifi_WifiSoftAPInfo, wifi_WifiSoftAPInfo, AUTO)


PB_BIND(wifi_WifiSoftAPList, wifi_WifiSoftAPList, 2)



